# 应用服务 WEB 访问端口
server:
  port: 8082
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myproject
    username: root
    password: root
  #session 失效时间
  session:
    timeout: 86400
    store-type: redis


  redis:
    port: 6379
    host: 192.168.6.100
    database: 0
    password: 123
  application:
    name: myproject-banckend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)